#!/bin/bash

function header {
    source $opnDirPath/header "${OpnDirVersion}" "${heading}"
}

function configs {
    source $opnDirPath/configs
}

function refreshScreen {
    tput clear
    header
}

function userInputs {
    refreshScreen
    tput cup 7 10
    read -p "Enter user name: " userName

    removemuser
}

function removemuser {

    sudo userdel -rf ${userName}
    refreshScreen
    tput cup 7 10
    echo -e "${userName} Management user removed successfully."
}


##########################################################################################################

heading="R E M O V E - M A N A G M E N T - U S E R"

header
configs
userInputs