#!/bin/bash

function logo {

    # clear the screen
    tput clear
    
    # Move cursor to screen location X,Y (top left is 0,0)
    tput cup 3 15
    
    # Set a foreground colour using ANSI escape
    tput setaf 3
    echo ${appName}
    tput sgr0
}

function heading {

    tput cup 5 15
    # Set reverse video mode
    tput rev
    echo ${heading}
    tput sgr0
}

##########################################################################################################

#user arguments
appName="$1"
heading="$2"

#trigger script
logo
heading